lib/media/index.js
Adds a call to get internally supported codecs for the media component.
=> added media codecs references

lib/deviceclasses/deviceclasses.json
As asked by @WeeJeWel in issue https://github.com/athombv/homey/issues/1527.
=> Adding capability measure_water

assets/capability/capabilities/windowcoverings_set.json
Units didn't pass parsing due to missing localizaiton
And some minor changes
=> Update units didn't pass parsing

lib/App/index.js
Z-Wave settings now include step size check for max values.
Athom eslint fixes applied as the Z-Wave checking function indentation wasn't correct.
Tested with two apps known to have problems related to this fix, both now work.
=> Setting max now divided by stepsize before checking the bounds

lib/App/index.js
Pretty please?... with sugar on top? :)
=> Adding support for Swedish

lib/App/index.js
Ooops.. Danish is da.. not dk.. my misstake!
=> Updated codes - Danish typo

lib/App/index.js
Strict mode does not allow functions declaration in a lexical nested statement.
Please push to production
=> Fix for Babel Strict mode error

assets/capability/capabilities/windowcoverings_tilt_down.json, assets/capability/capabilities/windowcoverings_tilt_set.json, assets/capability/capabilities/windowcoverings_tilt_up.json
Please merge to production as well.
=> Adds Dutch translations for window_coverings_tilt_set/up/down

.github/workflows/deploy.yml
This should also trigger an Action at athombv/node-homey
=> ci(deploy): add deploy.yml

lib/App/index.js
Reported here: https://athomcommunity.slack.com/archives/C04SUGZ9E/p1604949482190000
We where already filtering `arg.type !== 'device'`, fix is in 32cb73b where I check whether there are args remaining after filtering.
Cleaned up some of the if statements in the second commit best viewed without whitespace: https://github.com/athombv/node-homey-lib/pull/238/commits/5af8f4b0d61883c2492f2a8d0f4a0d6fe0639d94?w=1
=> fix: check args present

assets/capability/capabilities/meter_power.json
Also includes a locales patch: https://github.com/athombv/node-homey-lib/commit/86a7f995c61a25f2bfd020acb2dd056d4437cf03.
=> fix: check filtered args for presence #patch

assets/capability/capabilities/volume_set.json
Needs: https://github.com/athombv/homey-client/pull/1378 
Code is heavily inspired by it's `dim_relative` equivalent.
=> Add relative volume Flow action

assets/capability/capabilities/lock_mode.json, assets/capability/capabilities/thermostat_mode.json, assets/capability/capabilities/vacuumcleaner_state.json
Originating from: https://github.com/athombv/homey-apps-sdk-issues/issues/173#issuecomment-792284647
=> fix(thermostat-mode): inverted state of condition

assets/app/schema.json
This PR adds the ability to add `app.json->settings` to your Homey app. These are very similar to driver settings.
=> add app settings

lib/App/index.js
- dot is reserved to determine if something is a sub capability
=> feat: throw if capability id includes a dot

assets/capability/capabilities/measure_temperature.json, assets/capability/capabilities/meter_power.json
Super small change that adds a description for temperature. Are these translated automatically in other languages?
=> Added Temperature/Energy Description

lib/App/index.js
In the future this should be added to the schema.json, but showing a warning for now to keep backwards compatibility for now.
Todo:
=> feat(validate): add token type validation

lib/App/index.js
Enables Insights for the `garagedoor_closed` capability.
=> Update garagedoor_closed.json (#minor)

assets/device/classes/socket.json
Update "Plugged in" text strings according to design:
=> feat(plugged-in): Update translation strings.

assets/app/schema.json, test/validate-driver-manifest.js
Validation of endpoint keys did not work as expected.
=> Merge master into production (#patch)

assets/app/schema.json
Adds the ability to highlight specific driver settings.
=> feat(highlight-driver-setting): Add highlight prop

test/validate-capabilities.js
Added some test for system capabilities to make sure they are valid.
=> Test system capabilities
