athombv/node-homey-lib

lib/deviceclasses/deviceclasses.json

Adding additional capabilities for the Particulate Matter (Deeltjesvormige luchtverontreiniging) capabilities for both measure as well as alarm.
For the icons, I took the liberty to re-use the CO2 clouds (mirrored) and add some particles to it...
See attached ZIP:
[icons_pm25.zip](https://github.com/athombv/node-homey-lib/files/1258064/icons_pm25.zip)
A bit bigger then 2.5 um though ;-P

Add PM2.5 measure and alarm capabilities

---

assets/app/schema.json

Only needed for number settings.

added units i18n object to number/slider settings

---

lib/App/index.js

Prevent logging `[Object object]` which is not really helpful when debugging settings' signed values.

Improve logging

---

lib/App/index.js

This bug resulted in a very nice verbose error:
```
✓ Validating app...
✘ Homey App did not validate against level `debug`:
Cannot read property 'length' of undefined
Not installing, please fix the validation issues first
```

Check if array before looping

---

lib/App/index.js

I was able to publish an app that had a dangling symbolic link in `node_modules/` (left there because during development I used `npm link module`).
This PR adds an additional validation step, for "publish" validation only, to make sure there are no symlinks in `node_modules`.

Make sure node_modules/ doesn't contain symlinks when validating for publication

---

lib/App/index.js

from 
```
✖ Homey App did not validate against level `debug`:
[
{
"keyword": "maximum",
"dataPath": ".sdk",
"schemaPath": "#/properties/sdk/maximum",
"params": {
"comparison": "<=",
"limit": 2,
"exclusive": false
},
"message": "should be <= 2"
}
]
Not installing, please fix the validation issues first
```
to
```
✖ Homey App did not validate against level `debug`:
manifest.sdk should be <= 2
Not installing, please fix the validation issues first
```

Turn errors into readable text

---

lib/App/index.js
package-lock.json
package.json

This bumps the semver dependency from ^5.5.0 to ^5.7.0, as of 5.7.0 `semver.minVersion()` is available.

feat: validate compatibility for sdk v3 apps

---

lib/Energy/index.js

This PR adds the `C` type batteries: https://en.wikipedia.org/wiki/List_of_battery_sizes#Cylindrical_batteries as requested here: https://github.com/athombv/homey-apps-sdk-issues/issues/142

feat: add C type batteries

---

assets/capability/capabilities/alarm_contact.json
assets/capability/capabilities/alarm_motion.json

As far as I understand this is the place to indicate which kind of capabilitiesOptions there are. 
The 'zoneActivity' property is added for `alarm_contact` and `alarm_motion`.

Add options to disable zoneactivity

---

assets/app/schema.json
lib/App/index.js

~~Had to disable `additionalProperties: false` for the images schema. Would be better if we could only allow the optional "x-large" property, but could not find a way to do that with AJV (please correct me if I'm wrong).~~

feat: add optional image size x-large

---

assets/capability/capabilities.json
assets/capability/capabilities/garagedoor_closed.json
assets/capability/capabilities/onoff.json
assets/device/classes.json

Related issue: https://github.com/athombv/homey-apps-sdk-issues/issues/95
Took me awhile to get around to this one, turns out garagedoor was already defined, just not listed in the `classes.json` file. I also added it to the `onoff` capability so it has open / close actions.
Note that there is another device class that isn't listed: `relay`. I'm not sure whether we want to add that or not.

fix: enable garagedoor deviceclass

---

lib/App/index.js

homey-lib warns about a missing titleFormatted for the following flow, however the device argument is not a real argument so the only solution is to have a titleFormatted without arguments (same as the title).
```json
{
"title": {
"en": "Test title"
},
"args": [
{
"type": "device",
"name": "device",
"filter": "driver_id=test_driver"
}
]
}
```
In this PR we check the filtered arguments earlier and we bail out before the warning if we find no arguments that need to be in titleFormatted.
I did notice that `droptoken` is optional in titleFormatted, do we want to make this argument also required?
First commit contains the actual fix.
I'm not sure if this is what we want though, do we want to make titleFormatted required for all flow cards or only for those with arguments?

fix: title formatted warning

---

lib/App/index.js

This pr adds a validation step to error on permission `com.athom.homeyscript` which is not allowed.

feat: fail app validation on permission com.athom.homeyscript

---

assets/capability/capabilities/measure_pm25.json

fixes https://github.com/athombv/homey-apps-sdk-issues/issues/145
I also changed the unit from `m3` to `m³` because `m3` really makes no sense. Although I get that it is more readable.

Fix pm2.5 unit

---

assets/capability/capabilities/speaker_playing.json

fixes: https://github.com/athombv/homey-apps-sdk-issues/issues/199
Is it "stopped playing" or "was paused"?
I'm not sure how we get the other translations.
For many devices this status is not synced back to Homey so there are going to be cases where these Flow cards don't work... Maybe this is actually not such a good idea to add for all devices with `speaker_playing`?

feat: speaker_playing triggers

---

assets/capability/capabilities/meter_water.json

No of digits currently shown on Water Meter is only 2 , while the measurement from the device is in liters (3 digits).
So, if the proximity sensor 'sees' a signal, 1 liter was consumed, with 3 digits , this would be visible.
Caveat: not sure if in the past no of digits was lowered because maybe it did not fit for large numbers?

Increase no of digits on water meter to 3 to show litres on plate

---

assets/capability/schema.json

Capabilities need to be either `getable`, `setable` or both but our JSON schema doesn't validate that.
This PR updates the JSON Schema for capabilities to specify that a capability must have either `getable`, `setable` or both.

fix: require either getable or setable

---

lib/App/index.js

This is a warning instead of an error so existing apps continue to work, in the future this should be turned into a hard error.

feat: warn on duplicate Flow card ids

---

lib/App/index.js

I noticed a typo in BATTERY_CAPABILITIES - it is used to warn a developer when a device uses batteries but no battery type is specified in the manifest. This typo should also add this warning when using alarm_battery. ﻿

Fix Typo in battery capability

---

assets/capability/capabilities/garagedoor_closed.json

In Norwegian, `Opened` is `Åpnet` and not `Åpen`.
Using `Åpen` here would be like saying `I open the garage door` which is a bad choice of word

`garagedoor_closed_false` Norwegian title

---

lib/App/index.js

Missing `"platforms"` on a driver causes some very confusing behaviour when running an app on cloud.
We can't really error but we probably do want to warn that it is missing.

feat: warn if driver is missing platforms

---

.github/workflows/test.yml
README.md
package-lock.json
package.json
test/fixtures/mock-app.js
test/validate-base-manifest.js
test/validate-driver-manifest.js
test/validate-files.js

This PR adds a test suite to `homey-lib`. This currently consists of 66 passing tests.
Each of these tests generates a variation of an app with a different manifest (and different files on a "virtual"/"mock" filesystem). We then assert that an app has a certain validation error (or is valid) at all the validation levels.
So, currently, running all tests calls `HomeyLib.App#validate()` ~190 times. This takes about 10s to run in parallel, and about 15s sequentially.
Because creating all testcases is quite a bit of work not everything is tested, I chose to completely test the "base manifest" and some interesting properties of the "driver manifest" so we can use these tests to verify https://github.com/athombv/node-homey-lib/pull/329.
It might also be interesting to test some actual complete …

feat: add tests

---

assets/app/schema.json
lib/App/index.js
package.json
test/validate-base-manifest.js
test/validate-driver-manifest.js
test/validate-files.js

Remove the `requiredVerified` and `requiredPublish` options from the JSON Schema, the checks are moved to after AJV has checked the schema. This allows us to improve the error message to mention that the error is _because_ of the validation level.

fix: improve required errors for validation levels

---

helpers/index.js
lib/App/index.js

This fixes permission issues with images during `homey publish` since `homey` 2.33.5.

Make sure to close file descriptor after use

---

assets/app/schema.json
test/validate-driver-manifest.js

Validate that the `zigbee` object in a driver has the following shape:
```json
"zigbee": {
"manufacturerName": "manufName", // or array of strings
"productId": [ // or just a string
"productX"
],
"endpoints": {
"1": {
"clusters": [
0
],
"bindings": []
}
},
"learnmode": {
"image": "/drivers/product_x/assets/learnmode.svg",
"instruction": {
"en": "Instruction"
}
}
}
```

feat(zigbee): add validation

---

lib/App/index.js
test/validate-base-manifest.js
test/validate-driver-manifest.js

- Adds full path to checked images.
- Adds reference to which driver the error occurred for.
Before:
After:

fix(validation): improve image validation error message

---

assets/capability/capabilities/alarm_cleaning_pad_missing.json
assets/capability/capabilities/alarm_door_fault.json
assets/capability/capabilities/measure_hepa_filter.json
assets/capability/capabilities/mower_state.json
assets/capability/capabilities/target_humidity_max.json
assets/capability/capabilities/target_humidity_min.json
assets/capability/capabilities/target_temperature_max.json
assets/capability/capabilities/target_temperature_min.json

Flow triggers ending in `_true`, `_false` or `_checked` should start with the capability id.

Fix flow triggers for some new capabilities

---

lib/App/index.js

It doesn't make sense for home batteries to provide the type of built-in battery. It was intended for battery operated devices that should list the type of battery they use for easy replacement.

fix(validate): allow `homeBattery` devices to not provide `batteries` array

---

lib/App/index.js

Ensure that warnings for missing capabilities are only logged if the driver has the 'meter_power' capability when energy settings are enabled.

fix(driver): Add capability checks for energy settings warnings

---

lib/App/index.js

When checking for private prefix use in setting IDs, groups nested in another group were handled incorrectly:
If the group did not have an ID an error would occur due to calling .startsWith on undefined.
If the group did have an ID its children would not be checked for private prefix use.
I moved the check to a private method, which gets called recursively for child settings in groups.
Groups without IDs now no longer result in errors, and children with illegal prefixes result in a warning.

fix: check nested setting groups for private prefix use
